### ISSUE TITLE
Cannot find symbol N

### ISSUE THREAD

**Issue by LudgerPeters** [fizzed/ninja-rocker#1]
For some reason i am getting compilation issues when trying to compile my file with Ninja rocker.

it gives me the following error where ever i try use the N veriable.

[ERROR] /C:/work/personal/ninja-cdms/target/generated-sources/rocker/views/ApplicationController/index.java:[78,32] cannot find symbol
[ERROR] symbol:   variable N

Do i need to pass this n variable through some how?

**Comment by LudgerPeters** [comment]
added a gist with my rocker/html file and the generated java file:
https://gist.github.com/ludjer/4bd42dbfe9d3d1334a11

Also my maven build file contained the following:

```
        <plugin>
            <groupId>com.fizzed</groupId>
            <artifactId>rocker-maven-plugin</artifactId>
            <version>0.9.0</version>
            <executions>
                <execution>
                    <id>generate-rocker-templates</id>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                    <configuration>
                        <javaVersion>${java.version}</javaVersion>
                        <extendsClass>com.fizzed.ninja.rocker.NinjaRockerTemplate</extendsClass>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

**Comment by jjlauer** [comment]
Taking a peek at your generated Java source for index.java, I noticed it extends com.fizzed.rocker.runtime.DefaultRockerTemplate.

That's the reason the N variable isn't found.  It needs to extend com.fizzed.ninja.rocker.NinjaRockerTemplate.  

Now, you pasted code from your Maven pom where you configure the plugin and setup the extendsClass.  Are you positive that plugin is running with that configuration?   What does "mvn clean rocker:generate" yield for your generated index.java file?  Does it still extend DefaultRockerTemplate?

**Comment by jjlauer** [comment]
I also forgot to ask -- what version of Maven are you using?

I've also found issues not explicitly binding a plugin to a phase -- you may want to bind the plugin explicitly to the "generate-sources" phase to guarantee it executes.

**Comment by LudgerPeters** [comment]
maven version: 
       Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
       Maven home: C:\development\apache-maven-3.2.3
       Java version: 1.8.0_40, vendor: Oracle Corporation
       Java home: C:\Program Files\Java\jdk1.8.0_40\jre
       Default locale: en_ZA, platform encoding: Cp1252
       OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

tried clean and rocker:generate also did not work. 
I will try and upgrade my maven and see what happens. 
After i posted this issue i saw that it was extending the wrong class.

**Comment by jjlauer** [comment]
Maven 3.2.3 should be an acceptable version.

When I run "mvn rocker:generate" on one of my own projects, this is what it looks like:

```
joelauer@$ mvn rocker:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building web 3.0.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- rocker-maven-plugin:0.9.0:generate (default-cli) @ web ---
[INFO] Property rocker.javaVersion not set. Using your JDK version 1.8
[INFO] Parsing 8 rocker template files
[INFO] Generated 8 rocker java source files
[INFO] Added sources with /home/joelauer/workspace/fizzed/java-lauer-web/target/generated-sources/rocker
[INFO] Touching file /home/joelauer/workspace/fizzed/java-lauer-web/pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.821 s
[INFO] Finished at: 2015-04-13T09:31:43-07:00
[INFO] Final Memory: 17M/740M
[INFO] ------------------------------------------------------------------------
```

Once you get the plugin configured in your pom.xml correctly (which seems to be the culprit), it should just work for you.  If you share your full pom.xml -- I could probably pinpoint the issue quickly -- although if you can't for security reasons, you'll need to dig a bit more into the difference between my demo/pom.xml in this project vs. yours.

**Comment by LudgerPeters** [comment]
you can find my pom https://gist.github.com/ludjer/92e6e2d6b4f4066582be

thanks for the help.

**Comment by LudgerPeters** [comment]
Weird when i do a mvn compile it uses the correct class. However if i do a mvn rocker:generate it reverts to the other class.

**Comment by jjlauer** [comment]
Let's do 2 things:
1. Your maven-compiler plugin specifies java 1.7.  Switch that to have a source and target of 1.8 -- use the ${java.version} property you setup and pass into rocker.
2. Let's see if including a phase helps (this has helped me before).  Your execution block in the pom file will look like this:

```
<execution>
  <id>generate-rocker-templates</id>
  <phase>generate-sources</phase>
  <goals>
    <goal>generate</goal>
  </goals>
  <configuration>
    <javaVersion>${java.version}</javaVersion>
    <extendsClass>com.fizzed.ninja.rocker.NinjaRockerTemplate</extendsClass>
  </configuration>
</execution>
```

**Comment by LudgerPeters** [comment]
is this what you wanted me to do?

```
<executions>
    <execution>
        <id>generate-rocker-templates</id>
        <phase>generate-sources</phase>
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <javaVersion>${java.version}</javaVersion>
            <extendsClass>com.fizzed.ninja.rocker.NinjaRockerTemplate</extendsClass>
        </configuration>
    </execution>
</executions>
```

still gives exactly the same output.
When i do mvn compile it uses the correct NinjaRockerTemplate. But if i use the  rocker generate mvn command it returns i to the default.

I was able to replicate it on the ninja-rocker-demo project.
I first replaced the main project pom version from  <version>0.9.0-SNAPSHOT</version>
to <version>0.9.0</version> since it gave me errors about that.
I then proceeded to call rocker:generate and it gave me com.fizzed.rocker.runtime.DefaultRockerTemplate<index>.

I then called mvn clean folloed by mvn compile and then it used com.fizzed.ninja.rocker.NinjaRockerTemplate<index>

**Comment by jjlauer** [comment]
Gotcha.  If "mvn compile" works then that's what you want.  "mvn
rocker:generate" skips the specific execution with id and your overridden
configuration.  I think I gave you bad advice focusing on mvn
rocker:generate.

So, if mvn compile works, then I think you're all set?

**Comment by LudgerPeters** [comment]
yeah i am all set thanks for the help.
