### ISSUE TITLE
ninja context availability in subclasses of NinjaRockerTemplate

### ISSUE THREAD

**Issue by jshinobi** [fizzed/ninja-rocker#3]
I've use own subclass of NinjaRockerTemplate with a helper for views
and this helper need access to ninja context
Like this:
public abstract class LavinaRockerTemplate extends NinjaRockerTemplate {
...
public LavinaRocker L;
 @Override
    public void injectContext(NinjaProperties ninjaProperties, Router router, Messages messages, Lang lang, Context context, Result result) {
        super.injectContext(ninjaProperties, router, messages, lang, context, result);
        L = new LavinaRocker(ninjaProperties, router, messages, lang, result, context);
    }
...
}

**Comment by jjlauer** [comment]
Fixed in v0.12.0 - you persuaded me that context should be public.  You should also take a look at the new demonstration of Application-specific templates.

**Comment by jshinobi** [comment]
> Appreciate the PR, but I tweaked both Rocker and Ninja-Rocker do support everything a bit more elegantly. 

The PR was as an example.
This feature is so awesome, thanks a lot.
