### ISSUE TITLE
NullPointerException caused by @N.reverseRoute

### ISSUE THREAD

**Issue by awildturtok** [fizzed/ninja-rocker#5]
I've got Ninja and Rocker running and they have already been producing results. I wanted to include reverseRoutes in my page and used `<div>@N.reverseRoute(PerformanceController.class,"work","asdasd")</div>` to generate them. This always triggers NullPointerExceptions with the given the [following stacktrace](https://gist.github.com/awildturtok/812602892d8a58779d8e#file-stacktrace)

Evaluating line 10 of [work.rocker.html](https://gist.github.com/awildturtok/812602892d8a58779d8e#file-work-rocker-html) alone gives me "there", additionally the stacktrace says the NPE is somewhere else.

[Routes](https://gist.github.com/awildturtok/812602892d8a58779d8e#file-routes-java) is also setup to work I think.

I have all files I think are relevant In this gist: https://gist.github.com/awildturtok/812602892d8a58779d8e

I'm running on Windows 8 with Java 1.8 properly configured in Maven.

**Comment by jjlauer** [comment]
I'm not positive, but I think its simply the reverseRoute is not valid and
returning null back. Your route has a wildcard in it and I'm not sure Ninja
can populate it correctly so it simply returns null -- which causes the
NPE. Can you try a reverseRoute on your "classes" route instead (which is
more simple and should work).

-Joe

**Comment by awildturtok** [comment]
Yeah, this actually works. How would I setup my route to be not to specific, such that I could reverse route it? I have shrunk it down now to 

```
router.GET().route("/performance/{id}").with(PerformanceController.class,"view");
router.GET().route("/work/{id}").with(PerformanceController.class,"work");
```

But it still won't work. How would I go about it? I mean, wasn't reverse routing made specifically for that?

**Comment by jjlauer** [comment]
Those simpler versions _should_ most definitely work.  I believe you're
missing the parameter name.  So you need to pass the arguments as pairs.
Try this:

@N.reverseRoute(PerformanceController.class,"work","id", "asdasd")

**Comment by awildturtok** [comment]
Thank you! This works.
